// src/components/FindingDetail.vue
<script setup lang="ts">
import { computed, ref } from "vue";

import type { DetailAction, Finding, FindingType, LocalState } from "@/lib/types";
import { severityVar, shortId, timeAgo } from "@/lib/utils";

import Icon from "./Icon.vue";

type Props = {
  finding: Finding | null;
  types: Record<string, FindingType>;
  localState: LocalState;
};

type Emits = {
  action: [action: DetailAction, finding: Finding, payload?: string];
};

const props = defineProps<Props>();
const emit = defineEmits<Emits>();

const noteText = ref("");

type TimelineEvent = {
  kind: string;
  t: string;
  who?: string;
  body: string;
  extra?: string;
};

const type = computed(() => (props.finding ? props.types[props.finding.typeKind] : undefined));
const severityColor = computed(() => (type.value ? severityVar(type.value.severity) : undefined));

const timeline = computed<TimelineEvent[]>(() => {
  const finding = props.finding;
  if (!finding) return [];
  const localNotes = props.localState.notes[finding.findingId] ?? [];
  const items: TimelineEvent[] = [
    {
      kind: "evt-detect",
      t: finding.firstSeen,
      body: "Finding first detected by",
      who: finding.sensor,
    },
  ];
  if (finding.state === "acknowledged" && finding.ackedAt) {
    items.push({
      kind: "evt-ack",
      t: finding.ackedAt,
      body: "Acknowledged by",
      who: finding.ackedBy,
    });
  }
  if (finding.state === "snoozed" && finding.snoozedUntil) {
    items.push({
      kind: "evt-snooze",
      t: finding.lastSeen,
      body: "Snoozed by",
      who: finding.snoozedBy,
      extra: `until ${new Date(finding.snoozedUntil).toLocaleTimeString()}`,
    });
  }
  for (const note of localNotes) {
    items.push({
      kind: "evt-comment",
      t: note.at,
      body: "commented",
      who: note.by,
      extra: note.text,
    });
  }
  if (finding.state === "resolved" && finding.resolvedAt) {
    items.push({
      kind: "evt-resolve",
      t: finding.resolvedAt,
      body: "Resolved",
      extra: finding.resolvedReason,
    });
  }
  items.push({
    kind: "",
    t: finding.lastSeen,
    body: "Last occurrence — count now",
    who: `×${finding.count}`,
  });
  return items.sort((a, b) => new Date(a.t).getTime() - new Date(b.t).getTime());
});

const handleAction = (action: DetailAction) => {
  if (!props.finding) return;
  emit("action", action, props.finding);
};

const handlePostNote = () => {
  if (!props.finding) return;
  const trimmed = noteText.value.trim();
  if (!trimmed) return;
  emit("action", "comment", props.finding, trimmed);
  noteText.value = "";
};

const isMissing = (displayName?: string) => displayName?.startsWith("(missing") ?? false;

const handleGotoClick = (e: MouseEvent) => e.preventDefault();
</script>

<template>
  <div v-if="!finding" class="empty">
    <div class="glyph"><Icon name="bell" :size="15" /></div>
    <div>Select a finding to view details</div>
  </div>

  <template v-else>
    <div class="detail-header">
      <div class="kind-row">
        <span class="pill">{{ finding.typeKind }}</span>
        <span class="state-badge" :class="finding.state">{{ finding.state }}</span>
        <span :style="{ flex: 1 }" />
        <span class="uuid">{{ finding.findingId }}</span>
      </div>
      <h1>{{ finding.summary }}</h1>
      <div :style="{ display: 'flex', gap: '16px', fontSize: '12px', color: 'var(--text-dim)', flexWrap: 'wrap' }">
        <span>First seen <code>{{ timeAgo(finding.firstSeen) }}</code></span>
        <span>·</span>
        <span>Last seen <code>{{ timeAgo(finding.lastSeen) }}</code></span>
        <span>·</span>
        <span>Occurrences <code>×{{ finding.count }}</code></span>
        <span>·</span>
        <span>Severity <code :style="{ color: severityColor }">{{ type?.severity }}</code></span>
      </div>
    </div>

    <div class="actions">
      <button
        v-if="finding.state !== 'resolved' && finding.state !== 'acknowledged'"
        type="button"
        class="btn primary"
        @click="handleAction('ack')"
      >
        <Icon name="check" /> Acknowledge
      </button>
      <button
        v-if="finding.state !== 'snoozed' && finding.state !== 'resolved'"
        type="button"
        class="btn"
        @click="handleAction('snooze')"
      >
        <Icon name="snooze" /> Snooze 4h
      </button>
      <button type="button" class="btn" @click="handleAction('assign')">
        <Icon name="user" /> Assign…
      </button>
      <button v-if="finding.state === 'acknowledged'" type="button" class="btn" @click="handleAction('reopen')">
        Re-open
      </button>
      <button v-if="finding.state !== 'resolved'" type="button" class="btn" @click="handleAction('resolveModal')">
        <Icon name="resolve" /> Resolve…
      </button>
      <button type="button" class="btn" @click="handleAction('link')">
        <Icon name="external" /> Link ticket
      </button>
      <span :style="{ flex: 1 }" />
      <button type="button" class="btn ghost" aria-label="View API response">
        <span class="mono" :style="{ fontSize: '11px' }">
          GET /landscape/findings/{{ shortId(finding.findingId) }}…
        </span>
        <Icon name="external" />
      </button>
    </div>

    <div class="detail-body">
      <div v-if="finding.description || type?.description" class="section">
        <h3>Description</h3>
        <div class="desc">{{ finding.description || type?.description }}</div>
      </div>

      <div class="section">
        <h3>Finding class</h3>
        <div class="kv-grid">
          <dt>Class</dt>
          <dd>{{ finding.typeKind }}</dd>
          <dt>Class UUID</dt>
          <dd>{{ type?.id }}</dd>
          <dt>Phase</dt>
          <dd>phase 0 · structural integrity</dd>
          <dt>Auto-resolves</dt>
          <dd>yes — when referenced resource is registered</dd>
        </div>
      </div>

      <div class="section">
        <h3>Resources in this finding</h3>
        <div
          v-for="(resource, i) in finding.resources"
          :key="resource.resourceId"
          class="resource-card"
          :class="{ missing: isMissing(resource.displayName) }"
        >
          <span class="type-badge">{{ resource.resourceType }}</span>
          <div :style="{ minWidth: 0 }">
            <div class="name">
              <template v-if="i === 0">▸ </template>{{ resource.displayName }}
            </div>
            <div class="uuid">{{ resource.resourceId }}</div>
          </div>
          <a v-if="!isMissing(resource.displayName)" href="#" class="goto" @click="handleGotoClick">
            view <Icon name="external" />
          </a>
        </div>
      </div>

      <div class="section">
        <h3>Annotations</h3>
        <div>
          <span v-for="(a, i) in finding.annotations" :key="`${a.key}-${i}`" class="anno">
            <span class="k">{{ a.key }}</span>
            <span class="v">{{ a.value }}</span>
          </span>
        </div>
      </div>

      <div class="section">
        <h3>Activity</h3>
        <div class="timeline">
          <div v-for="(event, i) in timeline" :key="i" class="event" :class="event.kind">
            <div class="t">{{ timeAgo(event.t) }}</div>
            <div class="dot-col"><span class="dot" /></div>
            <div class="msg">
              {{ event.body }}<template v-if="event.who"> <span class="who">{{ event.who }}</span></template
              ><template v-if="event.extra && event.kind !== 'evt-comment' && event.kind !== 'evt-resolve'">
                {{ event.extra }}</template>
              <small v-if="event.extra && (event.kind === 'evt-comment' || event.kind === 'evt-resolve')">{{ event.extra }}</small>
            </div>
          </div>
        </div>
        <div class="composer">
          <textarea
            v-model="noteText"
            placeholder="Add a note… e.g. asked @maya to push the missing API manifest"
            aria-label="Add note"
          />
          <div class="composer-actions">
            <button type="button" class="btn ghost">Attach link</button>
            <button type="button" class="btn primary" @click="handlePostNote">
              <Icon name="comment" /> Post note
            </button>
          </div>
        </div>
      </div>
    </div>
  </template>
</template>

// components/FindingDetail.tsx
"use client";

import { useState, type ReactNode } from "react";

import type { Finding, FindingType, LocalState } from "@/lib/types";
import { classNames, severityVar, shortId, timeAgo } from "@/lib/utils";

import { Icon } from "./Icon";

export type DetailAction =
  | "ack"
  | "snooze"
  | "reopen"
  | "resolveModal"
  | "assign"
  | "link"
  | "comment";

export type ActionHandler = (
  action: DetailAction,
  finding: Finding | null,
  payload?: string
) => void;

type TimelineEvent = {
  kind: string;
  t: string;
  msg: ReactNode;
};

type FindingDetailProps = {
  finding: Finding | undefined;
  types: Record<string, FindingType>;
  localState: LocalState;
  onAction: ActionHandler;
};

export const FindingDetail = ({ finding, types, localState, onAction }: FindingDetailProps) => {
  const [noteText, setNoteText] = useState("");

  if (!finding) {
    return (
      <div className="empty">
        <div className="glyph">{Icon.bell}</div>
        <div>Select a finding to view details</div>
      </div>
    );
  }

  const type = types[finding.typeKind];
  const localNotes = localState.notes[finding.findingId] ?? [];

  const timeline: TimelineEvent[] = [
    {
      kind: "evt-detect",
      t: finding.firstSeen,
      msg: (
        <>
          Finding first detected by <span className="who">{finding.sensor}</span>
        </>
      ),
    },
    ...(finding.state === "acknowledged" && finding.ackedAt
      ? [
          {
            kind: "evt-ack",
            t: finding.ackedAt,
            msg: (
              <>
                Acknowledged by <span className="who">{finding.ackedBy}</span>
              </>
            ),
          } satisfies TimelineEvent,
        ]
      : []),
    ...(finding.state === "snoozed" && finding.snoozedUntil
      ? [
          {
            kind: "evt-snooze",
            t: finding.lastSeen,
            msg: (
              <>
                Snoozed by <span className="who">{finding.snoozedBy}</span> until{" "}
                <span className="who">{new Date(finding.snoozedUntil).toLocaleTimeString()}</span>
              </>
            ),
          } satisfies TimelineEvent,
        ]
      : []),
    ...localNotes.map(
      (n): TimelineEvent => ({
        kind: "evt-comment",
        t: n.at,
        msg: (
          <>
            <span className="who">{n.by}</span> commented
            <small>{n.text}</small>
          </>
        ),
      })
    ),
    ...(finding.state === "resolved" && finding.resolvedAt
      ? [
          {
            kind: "evt-resolve",
            t: finding.resolvedAt,
            msg: (
              <>
                Resolved
                <small>{finding.resolvedReason}</small>
              </>
            ),
          } satisfies TimelineEvent,
        ]
      : []),
    {
      kind: "",
      t: finding.lastSeen,
      msg: (
        <>
          Last occurrence — count now <span className="who">×{finding.count}</span>
        </>
      ),
    },
  ].sort((a, b) => new Date(a.t).getTime() - new Date(b.t).getTime());

  const handlePostNote = () => {
    const trimmed = noteText.trim();
    if (!trimmed) return;
    onAction("comment", finding, trimmed);
    setNoteText("");
  };

  const handleNoteChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => setNoteText(e.target.value);

  return (
    <>
      <div className="detail-header">
        <div className="kind-row">
          <span className="pill">{finding.typeKind}</span>
          <span className={`state-badge ${finding.state}`}>{finding.state}</span>
          <span style={{ flex: 1 }} />
          <span className="uuid">{finding.findingId}</span>
        </div>
        <h1>{finding.summary}</h1>
        <div style={{ display: "flex", gap: 16, fontSize: 12, color: "var(--text-dim)", flexWrap: "wrap" }}>
          <span>
            First seen <code>{timeAgo(finding.firstSeen)}</code>
          </span>
          <span>·</span>
          <span>
            Last seen <code>{timeAgo(finding.lastSeen)}</code>
          </span>
          <span>·</span>
          <span>
            Occurrences <code>×{finding.count}</code>
          </span>
          <span>·</span>
          <span>
            Severity <code style={{ color: severityVar(type?.severity ?? "low") }}>{type?.severity}</code>
          </span>
        </div>
      </div>

      <div className="actions">
        {finding.state !== "resolved" && finding.state !== "acknowledged" && (
          <button type="button" className="btn primary" onClick={() => onAction("ack", finding)}>
            {Icon.check} Acknowledge
          </button>
        )}
        {finding.state !== "snoozed" && finding.state !== "resolved" && (
          <button type="button" className="btn" onClick={() => onAction("snooze", finding)}>
            {Icon.snooze} Snooze 4h
          </button>
        )}
        <button type="button" className="btn" onClick={() => onAction("assign", finding)}>
          {Icon.user} Assign…
        </button>
        {finding.state === "acknowledged" && (
          <button type="button" className="btn" onClick={() => onAction("reopen", finding)}>
            Re-open
          </button>
        )}
        {finding.state !== "resolved" && (
          <button type="button" className="btn" onClick={() => onAction("resolveModal", finding)}>
            {Icon.resolve} Resolve…
          </button>
        )}
        <button type="button" className="btn" onClick={() => onAction("link", finding)}>
          {Icon.external} Link ticket
        </button>
        <span style={{ flex: 1 }} />
        <button type="button" className="btn ghost" aria-label="View API response">
          <span className="mono" style={{ fontSize: 11 }}>
            GET /landscape/findings/{shortId(finding.findingId)}…
          </span>{" "}
          {Icon.external}
        </button>
      </div>

      <div className="detail-body">
        {(finding.description ?? type?.description) && (
          <div className="section">
            <h3>Description</h3>
            <div className="desc">{finding.description ?? type?.description}</div>
          </div>
        )}

        <div className="section">
          <h3>Finding class</h3>
          <div className="kv-grid">
            <dt>Class</dt>
            <dd>{finding.typeKind}</dd>
            <dt>Class UUID</dt>
            <dd>{type?.id}</dd>
            <dt>Phase</dt>
            <dd>phase 0 · structural integrity</dd>
            <dt>Auto-resolves</dt>
            <dd>yes — when referenced resource is registered</dd>
          </div>
        </div>

        <div className="section">
          <h3>Resources in this finding</h3>
          {finding.resources.map((r, i) => {
            const missing = r.displayName?.startsWith("(missing");
            const handleGoto = (e: React.MouseEvent<HTMLAnchorElement>) => e.preventDefault();
            return (
              <div key={r.resourceId} className={classNames("resource-card", missing && "missing")}>
                <span className="type-badge">{r.resourceType}</span>
                <div style={{ minWidth: 0 }}>
                  <div className="name">
                    {i === 0 ? "▸ " : ""}
                    {r.displayName}
                  </div>
                  <div className="uuid">{r.resourceId}</div>
                </div>
                {!missing && (
                  <a href="#" className="goto" onClick={handleGoto}>
                    view {Icon.external}
                  </a>
                )}
              </div>
            );
          })}
        </div>

        <div className="section">
          <h3>Annotations</h3>
          <div>
            {finding.annotations.map((a, i) => (
              <span key={`${a.key}-${i}`} className="anno">
                <span className="k">{a.key}</span>
                <span className="v">{a.value}</span>
              </span>
            ))}
          </div>
        </div>

        <div className="section">
          <h3>Activity</h3>
          <div className="timeline">
            {timeline.map((event, i) => (
              <div key={i} className={classNames("event", event.kind)}>
                <div className="t">{timeAgo(event.t)}</div>
                <div className="dot-col">
                  <span className="dot" />
                </div>
                <div className="msg">{event.msg}</div>
              </div>
            ))}
          </div>
          <div className="composer">
            <textarea
              placeholder="Add a note… e.g. asked @maya to push the missing API manifest"
              value={noteText}
              onChange={handleNoteChange}
              aria-label="Add note"
            />
            <div className="composer-actions">
              <button type="button" className="btn ghost">
                Attach link
              </button>
              <button type="button" className="btn primary" onClick={handlePostNote}>
                {Icon.comment} Post note
              </button>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};
