// components/Modal.tsx
"use client";

import { useEffect, useState } from "react";

import type { Finding, ModalKind } from "@/lib/types";

export type ModalState = { kind: ModalKind; target: Finding };

type ModalConfig = { title: string; placeholder: string; cta: string };

const CONFIGS: Record<ModalKind, ModalConfig> = {
  resolve: {
    title: "Resolve finding",
    placeholder: 'Reason (e.g. "Product team pushed the missing API manifest")',
    cta: "Resolve",
  },
  assign: {
    title: "Assign finding",
    placeholder: "@username or team (e.g. @maya, team-payments)",
    cta: "Assign",
  },
  link: {
    title: "Link external ticket",
    placeholder: "https://jira.../PAY-1234 or github.com/…/issues/42",
    cta: "Link",
  },
};

type ModalProps = {
  modal: ModalState;
  onClose: () => void;
  onSubmit: (payload: string) => void;
};

export const Modal = ({ modal, onClose, onSubmit }: ModalProps) => {
  const [value, setValue] = useState("");
  const config = CONFIGS[modal.kind];

  useEffect(() => {
    const handleKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") onClose();
    };
    window.addEventListener("keydown", handleKey);
    return () => window.removeEventListener("keydown", handleKey);
  }, [onClose]);

  const handleSubmit = () => {
    const trimmed = value.trim();
    if (trimmed) onSubmit(trimmed);
  };

  const handleBackdropKeyDown = (e: React.KeyboardEvent<HTMLDivElement>) => {
    if (e.key === "Enter" || e.key === " ") {
      e.preventDefault();
      onClose();
    }
  };

  const handleModalClick = (e: React.MouseEvent<HTMLDivElement>) => e.stopPropagation();
  const handleValueChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => setValue(e.target.value);

  return (
    <div
      role="button"
      tabIndex={0}
      aria-label="Close modal"
      className="modal-backdrop"
      onClick={onClose}
      onKeyDown={handleBackdropKeyDown}
    >
      <div
        role="dialog"
        aria-modal="true"
        aria-label={config.title}
        className="modal"
        onClick={handleModalClick}
      >
        <h3>{config.title}</h3>
        <div style={{ fontSize: 12, color: "var(--text-dim)", marginBottom: 8 }}>
          {modal.target?.summary}
        </div>
        <textarea
          autoFocus
          value={value}
          onChange={handleValueChange}
          placeholder={config.placeholder}
          aria-label={config.title}
        />
        <div style={{ display: "flex", justifyContent: "flex-end", gap: 6, marginTop: 12 }}>
          <button type="button" className="btn ghost" onClick={onClose}>
            Cancel
          </button>
          <button type="button" className="btn primary" onClick={handleSubmit}>
            {config.cta}
          </button>
        </div>
      </div>
    </div>
  );
};

// src/components/Modal.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from "vue";

import type { Finding, ModalKind } from "@/lib/types";

type ModalConfig = { title: string; placeholder: string; cta: string };

const CONFIGS: Record<ModalKind, ModalConfig> = {
  resolve: {
    title: "Resolve finding",
    placeholder: 'Reason (e.g. "Product team pushed the missing API manifest")',
    cta: "Resolve",
  },
  assign: {
    title: "Assign finding",
    placeholder: "@username or team (e.g. @maya, team-payments)",
    cta: "Assign",
  },
  link: {
    title: "Link external ticket",
    placeholder: "https://jira.../PAY-1234 or github.com/…/issues/42",
    cta: "Link",
  },
};

type Props = { kind: ModalKind; target: Finding };
type Emits = { close: []; submit: [value: string] };

const props = defineProps<Props>();
const emit = defineEmits<Emits>();

const value = ref("");

const config = computed<ModalConfig>(() => CONFIGS[props.kind]);

const handleClose = () => emit("close");

const handleSubmit = () => {
  const trimmed = value.value.trim();
  if (!trimmed) return;
  emit("submit", trimmed);
};

const handleModalClick = (e: MouseEvent) => e.stopPropagation();

const handleBackdropKeyDown = (e: KeyboardEvent) => {
  if (e.key !== "Enter" && e.key !== " ") return;
  e.preventDefault();
  handleClose();
};

const handleDocKeyDown = (e: KeyboardEvent) => {
  if (e.key === "Escape") handleClose();
};

onMounted(() => window.addEventListener("keydown", handleDocKeyDown));
onUnmounted(() => window.removeEventListener("keydown", handleDocKeyDown));
</script>

<template>
  <div
    role="button"
    tabindex="0"
    aria-label="Close modal"
    class="modal-backdrop"
    @click="handleClose"
    @keydown="handleBackdropKeyDown"
  >
    <div
      role="dialog"
      aria-modal="true"
      :aria-label="config.title"
      class="modal"
      @click="handleModalClick"
    >
      <h3>{{ config.title }}</h3>
      <div :style="{ fontSize: '12px', color: 'var(--text-dim)', marginBottom: '8px' }">
        {{ props.target?.summary }}
      </div>
      <textarea
        v-model="value"
        autofocus
        :placeholder="config.placeholder"
        :aria-label="config.title"
      />
      <div :style="{ display: 'flex', justifyContent: 'flex-end', gap: '6px', marginTop: '12px' }">
        <button type="button" class="btn ghost" @click="handleClose">Cancel</button>
        <button type="button" class="btn primary" @click="handleSubmit">{{ config.cta }}</button>
      </div>
    </div>
  </div>
</template>
