// components/Sidebar.tsx
"use client";

import type { JSX } from "react";
import { Fragment } from "react";

import { classNames } from "@/lib/utils";
import type { ActiveView } from "@/lib/types";

import { Icon } from "./Icon";

export type SidebarCounts = {
  open: number;
  acknowledged: number;
  snoozed: number;
  resolved: number;
};

type NavItem = { id: ActiveView; label: string; icon: JSX.Element; count?: number };
type NavGroup = { group: string; items: NavItem[] };

type SidebarProps = {
  active: ActiveView;
  setActive: (view: ActiveView) => void;
  counts: SidebarCounts;
};

export const Sidebar = ({ active, setActive, counts }: SidebarProps) => {
  const nav: NavGroup[] = [
    {
      group: "Triage",
      items: [
        { id: "inbox", label: "Alert inbox", icon: Icon.bell, count: counts.open },
        { id: "acknowledged", label: "Acknowledged", icon: Icon.check, count: counts.acknowledged },
        { id: "snoozed", label: "Snoozed", icon: Icon.snooze, count: counts.snoozed },
        { id: "resolved", label: "Resolved", icon: Icon.resolve, count: counts.resolved },
      ],
    },
    {
      group: "Landscape",
      items: [
        { id: "explorer", label: "Model explorer", icon: Icon.map },
        { id: "sensors", label: "Sensors", icon: Icon.radar, count: 4 },
        { id: "classes", label: "Finding classes", icon: Icon.book, count: 6 },
        { id: "rules", label: "Filter rules", icon: Icon.filter, count: 6 },
      ],
    },
    {
      group: "System",
      items: [{ id: "settings", label: "Settings", icon: Icon.cog }],
    },
  ];

  const handleKeyDown = (id: ActiveView) => (e: React.KeyboardEvent<HTMLDivElement>) => {
    if (e.key === "Enter" || e.key === " ") {
      e.preventDefault();
      setActive(id);
    }
  };

  return (
    <aside className="sidebar" aria-label="Primary navigation">
      {nav.map((g) => (
        <Fragment key={g.group}>
          <div className="group">{g.group}</div>
          {g.items.map((item) => {
            const handleClick = () => setActive(item.id);
            return (
              <div
                key={item.id}
                role="button"
                tabIndex={0}
                aria-label={item.label}
                aria-current={active === item.id ? "page" : undefined}
                className={classNames("nav-item", active === item.id && "active")}
                onClick={handleClick}
                onKeyDown={handleKeyDown(item.id)}
              >
                {item.icon}
                <span>{item.label}</span>
                {item.count !== undefined && <span className="count">{item.count}</span>}
              </div>
            );
          })}
        </Fragment>
      ))}
    </aside>
  );
};

// src/components/Sidebar.vue
<script setup lang="ts">
import type { ActiveView } from "@/lib/types";

import Icon from "./Icon.vue";

export type SidebarCounts = {
  open: number;
  acknowledged: number;
  snoozed: number;
  resolved: number;
};

type IconName =
  | "bell"
  | "check"
  | "snooze"
  | "resolve"
  | "map"
  | "radar"
  | "book"
  | "cog"
  | "filter";

type NavItem = {
  id: ActiveView;
  label: string;
  icon: IconName;
  count?: number;
};

type NavGroup = { group: string; items: NavItem[] };

type Props = { active: ActiveView; counts: SidebarCounts };
type Emits = { activate: [view: ActiveView] };

const props = defineProps<Props>();
const emit = defineEmits<Emits>();

const nav = (): NavGroup[] => [
  {
    group: "Triage",
    items: [
      { id: "inbox", label: "Alert inbox", icon: "bell", count: props.counts.open },
      { id: "acknowledged", label: "Acknowledged", icon: "check", count: props.counts.acknowledged },
      { id: "snoozed", label: "Snoozed", icon: "snooze", count: props.counts.snoozed },
      { id: "resolved", label: "Resolved", icon: "resolve", count: props.counts.resolved },
    ],
  },
  {
    group: "Landscape",
    items: [
      { id: "explorer", label: "Model explorer", icon: "map" },
      { id: "sensors", label: "Sensors", icon: "radar", count: 4 },
      { id: "classes", label: "Finding classes", icon: "book", count: 6 },
      { id: "rules", label: "Filter rules", icon: "filter", count: 6 },
    ],
  },
  {
    group: "System",
    items: [{ id: "settings", label: "Settings", icon: "cog" }],
  },
];

const handleClick = (id: ActiveView) => emit("activate", id);

const handleKeyDown = (e: KeyboardEvent, id: ActiveView) => {
  if (e.key !== "Enter" && e.key !== " ") return;
  e.preventDefault();
  emit("activate", id);
};
</script>

<template>
  <aside class="sidebar" aria-label="Primary navigation">
    <template v-for="group in nav()" :key="group.group">
      <div class="group">{{ group.group }}</div>
      <div
        v-for="item in group.items"
        :key="item.id"
        role="button"
        tabindex="0"
        :aria-label="item.label"
        :aria-current="props.active === item.id ? 'page' : undefined"
        class="nav-item"
        :class="{ active: props.active === item.id }"
        @click="handleClick(item.id)"
        @keydown="(e: KeyboardEvent) => handleKeyDown(e, item.id)"
      >
        <Icon :name="item.icon" :size="15" />
        <span>{{ item.label }}</span>
        <span v-if="item.count !== undefined" class="count">{{ item.count }}</span>
      </div>
    </template>
  </aside>
</template>
